export const productTreeData = [
  {
    name: 'Phones',
    itemCount: 800,
    type: 'category',
    parent: null,
    parentName: null,
    child: true,
    id: 0,
    children: [
      {
        name: 'Apple',
        itemCount: 550,
        type: 'Brand',
        parent: 0,
        parentName: 'Phones',
        child: true,
        id: 1,
        children: [
          {
            name: 'iPhone 6',
            itemCount: 350,
            type: 'Model',
            parent: 1,
            parentName: 'Apple',
            child: true,
            id: 2,
            children: [
              {
                name: '128GB',
                itemCount: 200,
                type: 'Variant',
                parent: 2,
                parentName: 'iPhone 6',
                child: false,
                id: 3,
              },
              {
                name: '256GB',
                itemCount: 100,
                type: 'Variant',
                parent: 2,
                parentName: 'iPhone 6',
                child: false,
                id: 4,
              },
              {
                name: '512GB',
                itemCount: 50,
                type: 'Variant',
                parent: 2,
                parentName: 'iPhone 6',
                child: false,
                id: 5,
              },
            ],
          },
          {
            name: 'iPhone 7',
            itemCount: 200,
            type: 'item',
            parent: 1,
            parentName: 'Apple',
            child: true,
            id: 6,
            children: [
              {
                name: '128GB',
                itemCount: 200,
                type: 'Variant',
                parent: 6,
                parentName: 'iPhone 7',
                child: false,
                id: 7,
              },
            ],
          },
        ],
      },
      {
        name: 'Samsung',
        itemCount: 250,
        type: 'subCategory',
        parent: 0,
        parentName: 'Phones',
        child: false,
        id: 8,
      },
    ],
  },
  {
    name: 'Computers',
    itemCount: 700,
    type: 'category',
    parent: null,
    parentName: null,
    child: false,
    id: 9,
  },
  {
    name: 'Watches',
    itemCount: 350,
    type: 'category',
    parent: null,
    parentName: null,
    child: false,
    id: 10,
  },
  {
    name: 'TVs',
    itemCount: 70,
    type: 'category',
    parent: null,
    parentName: null,
    child: false,
    id: 11,
  },
];
